# Generated by Django 5.2.6 on 2025-09-25 11:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habits",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        blank=True, null=True, verbose_name="Место выполнения"
                    ),
                ),
                ("time", models.TimeField(verbose_name="Время выполнения")),
                ("action", models.CharField(verbose_name="Действие привычки")),
                (
                    "reward_action",
                    models.BooleanField(default=True, verbose_name="Приятная привычка"),
                ),
                (
                    "addition_habit",
                    models.TextField(verbose_name="Дополнение к привычке"),
                ),
                (
                    "period",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Число повторений в неделю"
                    ),
                ),
                (
                    "award",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Вознаграждение",
                    ),
                ),
                (
                    "time_to_action",
                    models.DurationField(
                        default=datetime.timedelta(seconds=120),
                        verbose_name="Время на выполнение",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True, verbose_name="Признак публичности"
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
            },
        ),
    ]
