# Generated by Django 5.2.6 on 2025-09-26 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atomic_habits", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habits",
            name="addition_habit",
            field=models.TextField(verbose_name="Связанная привычка"),
        ),
        migrations.AlterField(
            model_name="habits",
            name="reward_action",
            field=models.BooleanField(
                default=True, verbose_name="Признак приятной привычки"
            ),
        ),
    ]
