# Generated by Django 5.2.6 on 2025-09-26 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atomic_habits", "0003_alter_habits_addition_habit_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habits",
            name="addition_habit",
            field=models.CharField(
                blank=True, null=True, verbose_name="Связанная привычка"
            ),
        ),
    ]
