# Generated by Django 5.2.6 on 2025-09-30 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atomic_habits", "0004_alter_habits_addition_habit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habits",
            name="addition_habit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="atomic_habits.habits",
                verbose_name="Связанная привычка",
            ),
        ),
    ]
